language: java
jdk: openjdk14

before_script:
  - cd code
  - chmod +x mvnw

script: ./mvnw test -B

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - main
    - master
    - /^feature.*$/